version: '3'
services:
  postgresdb:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=books
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - '8081:8080'
    volumes:
      - ./swagger:/doc
    restart: always
    environment:
      SWAGGER_JSON: /doc/swagger.yml
      BASE_URL: /swagger
volumes:
  db:
