openapi: 3.0.0
info:
  title: Books API
  description: Books api
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: 'API Support'
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
servers:
  - url: http://localhost:8080/api
tags:
  - name: 'books'
    description: 'Api for books'
  - name: 'sigh-up'
    description: 'User registration'
  - name: 'sign-in'
    description: 'Login with email'

paths:
  /books:
    post:
      tags:
        - books
      summary: Create a book
      security:
        - bearerAuth: []
      requestBody:
        description: Create a book
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create-book'
      responses:
        '201':
          description: Create a book
          content:
            application/json:
              properties:
                data:
                  $ref: '#/components/schemas/book'
        '401':
          description: JWT token is not provided
          content:
            application/json:
              properties:
                data:
                  $ref: '#/components/schemas/unauthorized'
        '403':
          description: JWT token is not valid
          content:
            application/json:
              properties:
                data:
                  $ref: '#/components/schemas/unauthorized'
  /books/{id}:
    get:
      tags:
        - books
      summary: Get a book data
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: book Id
      responses:
        '200':
          description: a book data
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/book'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    book:
      properties:
        id:
          type: string
        title:
          type: string
        content:
          type: string
        lastPage:
          type: number
        author:
          type: string
    create-book:
      properties:
        id:
          type: string
        title:
          type: string
        content:
          type: string
        lastPage:
          type: number
        author:
          type: string
    unauthorized:
      properties:
        message:
          type: string
